[package]
name = "wadec-cli"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "wadec"
path = "src/main.rs"

[dependencies]
wadec = { path = ".." }
clap = { version = "4.5.53", features = ["derive"] }
patharg = "0.4.1"
thiserror = "2.0.17"
